modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="voxelium"
version="1.0.0"
displayName="Voxelium"
displayURL=""
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="AnhdVoxel74"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.voxelvariants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration

# End of user code block dependencies configuration
